# -*- coding: utf-8 -*-
"""preprocessing_raw_stopword.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHZuIopTIty-30ZQSFZUiXrx9idzzYA4
"""

import pandas as pd
import numpy as np

raw_stopword = pd.read_csv('./raw_stopword.csv' , index_col= 0)

print(raw_stopword.head())
print(raw_stopword.tail())
print(raw_stopword.info())
## 총 데이터 수 4963개

#  빈행 제거
raw_stopword.dropna(axis = 0,inplace=True)
print(raw_stopword.head())
print(raw_stopword.tail())
print(raw_stopword.info())

# 중복 데이터 제거

raw_stopword.drop_duplicates(inplace=True )
print(raw_stopword.head())
print(raw_stopword.tail())
print(raw_stopword.info())

stopword = raw_stopword.reset_index(drop = True)
print(stopword.info())
stopword

stopword.to_csv('./stopword.csv')

