# -*- coding: utf-8 -*-
"""해먹남녀_한식_양식.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4cT37bcZyzizD3yHP4zGPFUgHdOUm6m

1.   크롬 드라이버 버전  96.*
2.   삭제된 레시피하고 쓰레기 데이터 존재해서 데이터 전처리 좀 많이 필요해요
3.   영어 데이터 존재 / 빈 데이터 / 개쓰레기 데이터들 존재 (약 10% 내외)
"""

## 해먹남녀 한식

from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
import pandas as pd
import requests
import time
import re
from selenium.webdriver.support.ui import WebDriverWait

pd.set_option('display.unicode.east_asian_width', True)
options = webdriver.ChromeOptions()
options.add_argument('lang=ko_KR')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('disable-gpu')
driver = webdriver.Chrome('./chromedriver', options=options)
headers = {"User-Agent":'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'}
wait = WebDriverWait(driver, 10)
ingredient = ''
ingredients = []
category = ['Korean', 'Japanese', 'Chinese', 'Western']

for i in range(1,201):
    url = 'https://haemukja.com/recipes?category_group2%5B%5D=60&page={}'.format(i)
    for j in range(1, 13):
        driver.get(url)
        elem = driver.find_element_by_xpath('//*[@id="content"]/section/div[2]/div/ul/li[{}]/p/a'.format(j))
        new_url = elem.get_attribute("href")
        driver.get(new_url)
        try:
            for k in range(1, 40):
                a = driver.find_element_by_xpath(
                '/html/body/div/div[1]/div[2]/div/div[1]/section[1]/div/div[3]/ul/li[{}]/span'.format(k)).text
                ingredient = ingredient + ' ' + a
                ingredient = re.compile('[^가-힣|a-z|A-Z ]').sub(' ', ingredient)
        except:
            ingredients.append(ingredient)
            ingredient = ''
            df_section_titles = pd.DataFrame(ingredients, columns=['Ingredient'])
            df_section_titles['Category'] = category[0]


df_section_titles.to_csv('./korean.csv')
driver.close()

## 해먹남녀 양식

from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
import pandas as pd
import requests
import time
import re
from selenium.webdriver.support.ui import WebDriverWait


pd.set_option('display.unicode.east_asian_width', True)
options = webdriver.ChromeOptions()
options.add_argument('lang=ko_KR')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('disable-gpu')
driver = webdriver.Chrome('./chromedriver', options=options)
headers = {"User-Agent":'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'}
wait = WebDriverWait(driver, 10)
ingredient = ''
ingredients = []
category = ['Korean', 'Japanese', 'Chinese', 'Western']
# 91

for i in range(1,91):
    url = 'https://haemukja.com/recipes?category_group2%5B%5D=87&page={}'.format(i)
    
    for j in range(1, 13):
        driver.get(url)
        elem = driver.find_element_by_xpath('//*[@id="content"]/section/div[2]/div/ul/li[{}]/p/a'.format(j))
        new_url = elem.get_attribute("href")
        driver.get(new_url)
        try:
            for k in range(1, 40):
                a = driver.find_element_by_xpath(
                '/html/body/div/div[1]/div[2]/div/div[1]/section[1]/div/div[3]/ul/li[{}]/span'.format(k)).text
                ingredient += ' ' + a
                ingredient = re.compile('[^가-힣|a-z|A-Z ]').sub(' ', ingredient)
        except:
            ingredients.append(ingredient)
            ingredient = ''
            df_section_titles = pd.DataFrame(ingredients, columns=['Ingredient'])
            df_section_titles['Category'] = category[3]

df_section_titles.to_csv('./Western.csv')
driver.close()